#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Tool Executor Architecture

set -e

echo "========================================"
echo "Tool Executor Architecture - Dev Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if Go is installed
if ! command -v go &> /dev/null; then
    echo -e "${RED}Go is not installed. Please install Go 1.24.1 or later${NC}"
    exit 1
fi

# Check Go version
GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
echo -e "${GREEN}Go version: $GO_VERSION${NC}"

# Check if we're in the right directory
if [ ! -f "go.mod" ]; then
    echo -e "${RED}go.mod not found. Please run this script from the project root${NC}"
    exit 1
fi

# ============================================
# SETUP ENVIRONMENT
# ============================================

echo ""
echo "Setting up development environment..."

# Ensure pkg/toolexec directory exists
mkdir -p pkg/toolexec

# Download dependencies
echo "Downloading Go dependencies..."
go mod download

# Verify critical dependencies
echo "Verifying dependencies..."
go list -m golang.org/x/sync > /dev/null 2>&1 || echo -e "${YELLOW}Warning: golang.org/x/sync not found${NC}"
go list -m go.uber.org/mock > /dev/null 2>&1 || echo -e "${YELLOW}Warning: go.uber.org/mock not found${NC}"

# ============================================
# DEVELOPMENT COMMANDS
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Available Commands:"
echo ""
echo "  Build:"
echo "    go build ./pkg/toolexec/..."
echo ""
echo "  Test:"
echo "    go test ./pkg/toolexec/... -v          # Run all tests"
echo "    go test ./pkg/toolexec/... -cover      # With coverage"
echo "    go test ./pkg/toolexec/... -race       # Race detection"
echo ""
echo "  Code Quality:"
echo "    go vet ./pkg/toolexec/...              # Static analysis"
echo "    gofmt -l pkg/toolexec/                 # Check formatting"
echo "    gofmt -w pkg/toolexec/                 # Fix formatting"
echo ""
echo "  Coverage Report:"
echo "    go test ./pkg/toolexec/... -coverprofile=coverage.out"
echo "    go tool cover -html=coverage.out       # View in browser"
echo ""
echo "Current Working Directory: $(pwd)"
echo ""
